apiVersion: v1
kind: Service
metadata:
  name: go-boilerplate-service
spec:
  selector:
    app: go-boilerplate-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
