name: prod-deployment

on:
  push:
    branches:
      - prod


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v4
        with: 
          go-version: 1.21.5
      - name: Unit Test
        run: go test -timeout 60s ./tests/...
      - name: Install Package
        run: go get .
      - name: Build Go 
        run: go build -o ./dist/main .  
      - name: Version Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
      - name: Create A GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: ./dist/main

  docker-build:
      runs-on: ubuntu-latest
      needs: deployment
      steps:
        - uses: actions/checkout@v4
        - name: Build Image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: dockerfiles/prod.dockerfile
            push: true
            tags: saddamsatria/go-boilerplate:${{steps.tag_version.outputs.new_tag}}:
        



            